favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites'

urlpatterns = [
    path('adicionar/<int:receita_id>/', views.adicionar_favoritos, name='adicionar_favoritos'),
    path('remover/<int:receita_id>/', views.remover_favorito, name='remover_favorito'),
    path('favoritas/', views.receitas_favoritas, name='receitas_favoritas'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('configuracoes/', views.configuracoes, name='configuracoes'),
]

recipes/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.lista_receitas, name='lista_receitas'),
    path('cadastrar/', views.cadastrar_receita, name='cadastrar_receita'),
    path('<int:receita_id>/', views.detalhes_receita, name='detalhes_receita'),
    path('excluir/<int:receita_id>/', views.excluir_receita, name='excluir_receita'),
    path('editar/<int:receita_id>/', views.editar_receita, name='editar_receita'),
    path('recomendadas/', views.receitas_recomendadas, name='receitas_recomendadas'),
    path('compartilhar/<int:receita_id>/', views.compartilhar_receita, name='compartilhar_receita'),
    path('aprovar_receita/<int:receita_id>/', views.aprovar_receita, name='aprovar_receita'),
    path('receitas_pendentes/', views.lista_pendentes, name='lista_pendentes'),
]

swiftsavor/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('recipes/', include('recipes.urls')),
    path('users/', include('users.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('admin_tools/', include('admin_tools.urls')),
    path('favorites/', include('favorites.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from ingredients.models import Ingrediente
from django.utils import timezone

class Receita(models.Model):
    nome = models.CharField(max_length=200)
    ingredientes = models.ManyToManyField(Ingrediente)
    instruções = models.TextField()
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    data_cadastro = models.DateField(auto_now_add=False, default=timezone.now)
    aprovada = models.BooleanField(default=False)

    def __str__(self):
        return self.nome
    

class ImagemReceita(models.Model):
    receita = models.ForeignKey(Receita, related_name='imagens_receita', on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='receitas/', null=True, blank=True)
    url = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"Imagem para {self.receita.nome}"
    

recipes/forms.py
from django import forms
from .models import Receita, ImagemReceita, Ingrediente
from django.forms import modelformset_factory

class ReceitaForm(forms.ModelForm):
    class Meta:
        model = Receita
        fields = ['nome', 'instruções', 'ingredientes']
    
    ingredientes = forms.ModelMultipleChoiceField(
        queryset=Ingrediente.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False
    )

ImagemReceitaFormSet = modelformset_factory(
    ImagemReceita,
    fields=('imagem','url'),
    extra=3, 
    max_num=5,
    widgets={
        'imagem': forms.FileInput(attrs={'class': 'form-control'}),
        'url': forms.URLInput(attrs={'class': 'form-control'}),
        }
)

class PesquisaReceitaForm(forms.Form):
    pesquisa = forms.CharField(max_length=100, required=False, label='Pesquisar')


class EditarReceitaForm(forms.ModelForm):
    ingredientes = forms.ModelMultipleChoiceField(
        queryset=Ingrediente.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
        required=False
    )

    class Meta:
        model = Receita
        fields = ['nome', 'instruções', 'ingredientes']

class EditarImagemReceitaForm(forms.ModelForm):
    class Meta:
        model = ImagemReceita
        fields = ['imagem', 'url']

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from .models import Receita, ImagemReceita
from .forms import EditarImagemReceitaForm, EditarReceitaForm, PesquisaReceitaForm, ReceitaForm, ImagemReceitaFormSet
from ingredients.models import Ingrediente,UsuarioIngrediente
from urllib.parse import quote
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from favorites.models import ReceitaFavorita
from django.forms import modelformset_factory
from django.forms import inlineformset_factory


@login_required
def lista_receitas(request):
    form_pesquisa = PesquisaReceitaForm(request.GET)
    receitas = Receita.objects.filter(aprovada=True)

    if form_pesquisa.is_valid():
        termo_pesquisa = form_pesquisa.cleaned_data['pesquisa']
        receitas = receitas.filter(nome__icontains=termo_pesquisa)

    receitas = receitas.order_by('nome')

    if request.user.is_authenticated:
        receitas_favoritas_ids = list(
            ReceitaFavorita.objects.filter(usuario=request.user).values_list('receita__id', flat=True)
        )
    else:
        receitas_favoritas_ids = []

    paginator = Paginator(receitas, 10)
    page = request.GET.get('page')

    try:
        receitas = paginator.page(page)
    except PageNotAnInteger:
        receitas = paginator.page(1)
    except EmptyPage:
        receitas = paginator.page(paginator.num_pages)

    return render(request, 'recipes/lista_receitas.html', {'receitas': receitas, 'form_pesquisa': form_pesquisa, 'receitas_favoritas_ids': receitas_favoritas_ids})


@login_required
def cadastrar_receita(request):
    if request.method == 'POST':
        form = ReceitaForm(request.POST, request.FILES)
        formset = ImagemReceitaFormSet(request.POST, request.FILES)

        if form.is_valid() and formset.is_valid():
            receita = form.save(commit=False)
            receita.usuario = request.user
            receita.aprovada = False
            receita.save()
            form.save_m2m()

            for form_imagem in formset.cleaned_data:
                imagem = form_imagem.get('imagem')
                url = form_imagem.get('url')
                if imagem:
                    ImagemReceita.objects.create(receita=receita, imagem=imagem)
                elif url:
                    ImagemReceita.objects.create(receita=receita, url=url)    

            messages.success(request, 'Receita cadastrada com sucesso! Aguardando aprovação.')
            return redirect('lista_receitas')
    else:
        form = ReceitaForm()
        formset = ImagemReceitaFormSet(queryset=ImagemReceita.objects.none())

    return render(request, 'recipes/cadastrar_receita.html', {'form': form, 'formset': formset})


@login_required
def editar_receita(request, receita_id):
    receita = get_object_or_404(Receita, id=receita_id)
    ImagemReceitaFormSet = inlineformset_factory(Receita, ImagemReceita, form=EditarImagemReceitaForm, extra=1, can_delete=True)

    if request.method == 'POST':
        form = EditarReceitaForm(request.POST, instance=receita)
        formset_imagem = ImagemReceitaFormSet(request.POST, request.FILES, instance=receita)

        if form.is_valid() and formset_imagem.is_valid():
            form.save()
            formset_imagem.save()
            messages.success(request, 'Receita editada com sucesso.')
            return redirect('detalhes_receita', receita_id=receita_id)
    else:
        form = EditarReceitaForm(instance=receita)
        formset_imagem = ImagemReceitaFormSet(instance=receita)

    return render(request, 'recipes/editar_receita.html', {'form': form, 'formset_imagem': formset_imagem, 'receita': receita})




@user_passes_test(lambda u: u.is_staff, login_url='index')
def excluir_receita(request, receita_id):
    receita = get_object_or_404(Receita, id=receita_id)
    if request.method == 'POST':
        receita.delete()
        messages.success(request, 'Receita excluída com sucesso.')
        return redirect('lista_receitas')
    return render(request, 'recipes/excluir_receita.html', {'receita': receita})


@login_required
def detalhes_receita(request, receita_id):
    receita = get_object_or_404(Receita, pk=receita_id)

    ingredientes_usuario_ids = UsuarioIngrediente.objects.filter(
        usuario=request.user
    ).values_list('ingrediente_id', flat=True)
    
    ingredientes_faltando = receita.ingredientes.exclude(id__in=ingredientes_usuario_ids)

    return render(request, 'recipes/detalhes_receita.html', {'receita': receita, 'ingredientes_faltando': ingredientes_faltando})


@login_required
def receitas_recomendadas(request):
    ingredientes_usuario_ids = UsuarioIngrediente.objects.filter(
        usuario=request.user
    ).values_list('ingrediente_id', flat=True)

    receitas_possiveis = Receita.objects.filter(
        ingredientes__id__in=ingredientes_usuario_ids,
        aprovada=True
    ).distinct()

    receitas_completas = []
    for receita in receitas_possiveis:
        ingredientes_receita_ids = set(receita.ingredientes.values_list('id', flat=True))
        if ingredientes_receita_ids.issubset(ingredientes_usuario_ids):
            receitas_completas.append(receita)

    paginator = Paginator(receitas_completas, 10)
    page = request.GET.get('page')

    try:
        receitas = paginator.page(page)
    except PageNotAnInteger:
        receitas = paginator.page(1)
    except EmptyPage:
        receitas = paginator.page(paginator.num_pages)

    receitas_favoritas_ids = list(
        ReceitaFavorita.objects.filter(usuario=request.user).values_list('receita__id', flat=True)
    )

    return render(request, 'recipes/receitas_recomendadas.html', {'receitas': receitas, 'receitas_favoritas_ids': receitas_favoritas_ids})

@login_required
def compartilhar_receita(request, receita_id):
    receita = get_object_or_404(Receita, pk=receita_id)
    link_unido = request.build_absolute_uri(reverse('detalhes_receita', args=[receita_id]))
    link_whatsapp = f'https://api.whatsapp.com/send?text={quote(link_unido)}'

    return render(request, 'recipes/compartilhar_receita.html', {'receita': receita, 'link_whatsapp': link_whatsapp})



@user_passes_test(lambda u: u.is_staff, login_url='index')
def aprovar_receita(request, receita_id):
    receita = get_object_or_404(Receita, id=receita_id)
    
    if request.method == 'POST':
        receita.aprovada = True
        receita.save()
        messages.success(request, 'Receita aprovada com sucesso.')
        return redirect('lista_pendentes')

    return render(request, 'recipes/detalhes_receita.html', {'receita': receita})


@user_passes_test(lambda u: u.is_staff, login_url='index')
def lista_pendentes(request):
    receitas_pendentes = Receita.objects.filter(aprovada=False)
    return render(request, 'recipes/lista_pendentes.html', {'receitas_pendentes': receitas_pendentes})

recipes/templates/recipes/cadastrar_receita.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-fluid mt-4 d-flex justify-content-center align-items-center">
    <div class="card mb-4 cadastro-receita-card">
        <div class="card-body">
            <h1 class="card-title mb-4">Cadastrar Receita</h1>
            <p class="card-text">• Após cadastrar a receita, ela ficará pendente de aprovação por um administrador.</p>
            
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ formset.management_form }}
                {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label }}" class="col-12 form-label" id="label-receita-form">{{ field.label }}:</label>
                    <div class="col-12">
                        {{ field }}
                    </div>
                    {% if field.help_text %}
                    <small class="col-12 form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {{ field.errors }}
                </div>
                {% endfor %}

                <input type="text" id="search-ingredient" class="form-control col-12" placeholder="Pesquisar ingredientes" aria-label="Pesquisar ingredientes" aria-describedby="search-ingredient-desc">
                <small id="search-ingredient-desc" class="col-12 form-text text-muted">Use este campo para pesquisar ingredientes.</small>
                
                {% for formset_form in formset %}
                <div class="form-group row">
                    <div class="col-12">
                        {{ formset_form.as_p }}
                    </div>
                    {% for field in formset_form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>
                {% endfor %}
                
                <div class="form-group row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-cadastrar" aria-label="Cadastrar">Cadastrar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function(){
        $("#search-ingredient").on("input", function() {
            var searchTerm = $(this).val().toLowerCase();

            if (searchTerm === "") {
                $("div[id^='id_ingredientes'] > div").hide();
                $("input[name='ingredientes']:checked").each(function() {
                    $(this).closest('div').show();
                });
            } else {
                $("div[id^='id_ingredientes'] > div").hide();

                $("div[id^='id_ingredientes'] > div:contains-ci(" + searchTerm + ")").show();
            }
        });

        $.extend($.expr[":"], {
            "contains-ci": function(elem, i, match, array) {
                return (elem.textContent || elem.innerText || "").toLowerCase().indexOf((match[3] || "").toLowerCase()) >= 0;
            }
        });

        $("div[id^='id_ingredientes'] > div").hide();
    });
</script>
{% endblock %}

recipes/templates/recipes/detalhes_receita.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-fluid detalhes-receita">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header detalhes-receita-header">
                    <h1>{{ receita.nome }}</h1>
                </div>
                <div class="card-body detalhes-receita-body">
                    <div id="carouselReceita" class="carousel slide custom-carousel mb-3" data-ride="carousel" data-interval="false">
                        <div class="carousel-inner">
                            {% for imagem in receita.imagens_receita.all %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    {% if imagem.imagem %}
                                        <img src="{{ imagem.imagem.url }}" class="d-block w-100" alt="{{ receita.nome }}">
                                    {% elif imagem.url %}
                                        <img src="{{ imagem.url }}" class="d-block w-100" alt="{{ receita.nome }}">
                                    {% else %}
                                        <p>Nenhuma imagem disponível.</p>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                        <a class="carousel-control-prev" href="#carouselReceita" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Anterior</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselReceita" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Próximo</span>
                        </a>
                    </div>

                    <div class="card mb-3 detalhes-receita-card col-md-8 mx-auto">
                        <div class="card-header detalhes-receita-card-header w-100">
                            <h2>Lista de Compras</h2>
                        </div>
                        <div class="card-body detalhes-receita-card-body">
                            <div class="detalhes-receita-compras">
                                {% if ingredientes_faltando %}
                                    <p class="mb-0">Você precisará dos seguintes ingredientes:</p>
                                    <ul class="list-group mt-2">
                                        {% for ingrediente in ingredientes_faltando %}
                                            <li class="list-group-item detalhes-receita-item">{{ ingrediente.nome }}</li>
                                        {% endfor %}
                                    </ul>

                                    <!-- Botão para compartilhar a lista de compras pelo WhatsApp -->
                                    <div class="text-center mt-3">
                                        <a href="https://api.whatsapp.com/send?text=Para%20preparar%20a%20receita%20{{ receita.nome }},%20você%20precisa%20dos%20seguintes%20ingredientes:%0A{% for ingrediente in ingredientes_faltando %}{{ ingrediente.nome }}%0A{% endfor %}" class="btn btn-whatsapp">
                                            Compartilhar Lista de Compras no WhatsApp
                                        </a>
                                    </div>
                                    
                                {% else %}
                                    <p>Você tem todos os ingredientes para fazer esta receita!</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="card mb-3 detalhes-receita-card col-md-8 mx-auto">
                        <div class="card-header detalhes-receita-card-header">
                            <h2>Ingredientes</h2>
                        </div>
                        <div class="card-body detalhes-receita-card-body">
                            <ul class="detalhes-receita-ingredientes list-group mt-3">
                                {% for ingrediente in receita.ingredientes.all %}
                                    <li class="detalhes-receita-item list-group-item">{{ ingrediente.nome }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>

                    <h2>Instruções:</h2>
                    <p class="detalhes-receita-instrucoes">{{ receita.instruções }}</p>
                    <h2>Informações Adicionais:</h2>
                    <p class="detalhes-receita-info"><strong>Data de Cadastro:</strong> {{ receita.data_cadastro|date:"d/m/Y" }}</p>
                    {% if receita.usuario %}
                        <p class="detalhes-receita-info"><strong>Cadastrado por:</strong> {{ receita.usuario.username }}</p>
                    {% else %}
                        <p class="detalhes-receita-info"><strong>Cadastrado por:</strong> Usuário desconhecido</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="text-center mt-3 detalhes-receita-whatsapp">
    <a href="https://api.whatsapp.com/send?text=Confira+a+receita:+{{ receita.nome }}+{{ request.build_absolute_uri }}" class="btn btn-whatsapp">
        Compartilhar no WhatsApp
    </a>
</div>
{% endblock %}

recipes/templates/recipes/excluir_receita.html
{% extends 'main/base.html' %}

{% block title %}
    Confirmar Exclusão de Receita
{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">Confirmar Exclusão</h1>
        <p>Você está prestes a excluir a receita: <strong>{{ receita.nome }}</strong>.</p>
        <p>Tem certeza de que deseja continuar?</p>

        <form method="post" action="{% url 'excluir_receita' receita.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Sim, Excluir</button>
            <a href="{% url 'lista_receitas' %}" class="btn btn-secondary">Cancelar</a>
        </form>
    </div>
{% endblock %}

recipes/templates/recipes/lista_pendentes.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-fluid mt-4 receitas-pendentes-container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h1 class="mb-4 text-center">Receitas Pendentes de Aprovação</h1>
            <div class="card">
                <div class="card-body">

                    {% if receitas_pendentes %}
                        <ul class="list-group">
                            {% for receita in receitas_pendentes %}
                                <li class="list-group-item">
                                    <a href="{% url 'detalhes_receita' receita.id %}">{{ receita.nome }}</a>
                                    <form method="post" action="{% url 'aprovar_receita' receita.id %}" class="d-inline">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-success btn-sm float-right">Aprovar Receita</button>
                                    </form>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p class="text-center no-receitas-message">Nenhuma receita pendente de aprovação no momento.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

recipes/templates/recipes/lista_receitas.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-fluid mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-4">
            <h1 class="mb-4 text-center">Lista de Receitas</h1>

            <form method="get" action="{% url 'lista_receitas' %}" class="form-group-listar">
                <div class="input-group d-flex">
                    <input type="text" name="pesquisa" id="id_pesquisa" class="form-control" placeholder="Pesquisar" aria-label="Pesquisar" aria-describedby="botao-pesquisar">
                    <button type="submit" class="btn btn-primary btn-pesquisar" id="botao-pesquisar">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </form>
            

            {% if messages %}
                <ul class="messages" role="alert">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <ul class="list-group listagem-receitas">
                {% for receita in receitas %}
                    <li class="list-group-item">
                        <div class="recipe-info">
                            <a href="{% url 'detalhes_receita' receita.id %}">{{ receita.nome }}</a>
                        </div>
                        {% if not user.is_authenticated or not user.is_staff %}
                            <form method="post" class="d-inline">
                                {% csrf_token %}
                                {% if receita.id in receitas_favoritas_ids %}
                                    <input type="hidden" name="receita_id" value="{{ receita.id }}">
                                    <button type="submit" formaction="{% url 'favorites:remover_favorito' receita.id %}" class="btn btn-primary btn-sm align-self-center btn-remove-favoritos" aria-label="Remover dos favoritos">
                                        <i class="fas fa-heart" aria-hidden="true"></i>
                                    </button>
                                {% else %}
                                    <button type="submit" formaction="{% url 'favorites:adicionar_favoritos' receita.id %}" class="btn btn-primary btn-sm align-self-center btn-favoritos" aria-label="Adicionar aos favoritos">
                                        <i class="far fa-heart" aria-hidden="true"></i>
                                    </button>
                                {% endif %}
                            </form>
                        {% endif %}
                        {% if user.is_authenticated and user.is_staff %}
                            <div class="admin-actions">
                                <a href="{% url 'editar_receita' receita.id %}" class="btn btn-warning btn-sm" aria-label="Editar Receita">Editar Receita</a>
                                <form method="post" action="{% url 'excluir_receita' receita.id %}" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm ml-2" aria-label="Excluir Receita">Excluir Receita</button>
                                </form>
                            </div>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>

                <div class="card pagination-card">
                    <div class="card-body">
                        <nav aria-label="Navegação de páginas" class="pagination justify-content-center">
                            <ul class="pagination-list">
                                {% if receitas.has_previous %}
                                    <li class="page-item">
                                        <a href="?page=1">&laquo; primeira</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="?page={{ receitas.previous_page_number }}">anterior</a>
                                    </li>
                                {% endif %}
                        
                                <li class="page-item">
                                    <span class="current">Página {{ receitas.number }} de {{ receitas.paginator.num_pages }}.</span>
                                </li>
                        
                                {% if receitas.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ receitas.next_page_number }}">próxima</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="?page={{ receitas.paginator.num_pages }}">última &raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>

        </div>
    </div>
</div>
{% endblock %}

recipes/templates/recipes/receitas_recomendadas.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container-fluid mt-4 receitas-recomendadas-container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <h2 class="mb-4 text-center receitas-recomendadas-title">Receitas Recomendadas</h2>

            {% if messages %}
                <ul class="messages list-group">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }} list-group-item"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            {% if receitas %}
                <ul class="list-group">
                    {% for receita in receitas %}
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <a href="{% url 'detalhes_receita' receita.id %}">{{ receita.nome }}</a>
                            {% if receita.id in receitas_favoritas_ids %}
                                <form method="post" action="{% url 'favorites:remover_favorito' receita.id %}" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" formaction="{% url 'favorites:remover_favorito' receita.id %}" class="btn btn-primary btn-sm float-right align-self-center btn-remove-favoritos" aria-label="Remover dos favoritos">
                                        <i class="fas fa-heart"></i>
                                    </button>
                                </form>
                            {% else %}
                                <form method="post" action="{% url 'favorites:adicionar_favoritos' receita.id %}" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" formaction="{% url 'favorites:adicionar_favoritos' receita.id %}" class="btn btn-primary btn-sm float-right align-self-center btn-favoritos" aria-label="Adicionar aos favoritos">
                                        <i class="far fa-heart"></i>
                                    </button>
                                </form>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
                
                <div class="card pagination-card">
                    <div class="card-body">
                        <nav aria-label="Navegação de páginas" class="pagination justify-content-center">
                            <ul class="pagination-list">
                                {% if receitas.has_previous %}
                                    <li class="page-item">
                                        <a href="?page=1">&laquo; primeira</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="?page={{ receitas.previous_page_number }}">anterior</a>
                                    </li>
                                {% endif %}
                        
                                <li class="page-item">
                                    <span class="current">Página {{ receitas.number }} de {{ receitas.paginator.num_pages }}.</span>
                                </li>
                        
                                {% if receitas.has_next %}
                                    <li class="page-item">
                                        <a href="?page={{ receitas.next_page_number }}">próxima</a>
                                    </li>
                                    <li class="page-item">
                                        <a href="?page={{ receitas.paginator.num_pages }}">última &raquo;</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            {% else %}
                <p>Não foram encontradas receitas com os ingredientes que você possui.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}