favorites/urls.py
from django.urls import path
from . import views

app_name = 'favorites'

urlpatterns = [
    path('adicionar/<int:receita_id>/', views.adicionar_favoritos, name='adicionar_favoritos'),
    path('remover/<int:receita_id>/', views.remover_favorito, name='remover_favorito'),
    path('favoritas/', views.receitas_favoritas, name='receitas_favoritas'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('configuracoes/', views.configuracoes, name='configuracoes'),
]

swiftsavor/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('recipes/', include('recipes.urls')),
    path('users/', include('users.urls')),
    path('ingredients/', include('ingredients.urls')),
    path('admin_tools/', include('admin_tools.urls')),
    path('favorites/', include('favorites.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.utils import timezone

class Ingrediente(models.Model):
    nome = models.CharField(max_length=200)

    def __str__(self):
        return self.nome
    
class UsuarioIngrediente(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    quantidade = models.IntegerField(default=0)

    class Meta:
        unique_together = ('usuario', 'ingrediente')

    def __str__(self):
        return f"{self.usuario.username} - {self.ingrediente.nome}"    

class Receita(models.Model):
    nome = models.CharField(max_length=200)
    ingredientes = models.ManyToManyField(Ingrediente)
    instrucoes = models.TextField()
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    data_cadastro = models.DateField(auto_now_add=False, default=timezone.now)

    def __str__(self):
        return self.nome

    
class ImagemReceita(models.Model):
    receita = models.ForeignKey(Receita, related_name='imagens_receita', on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='receitas/')

    def __str__(self):
        return f"Imagem para {self.receita.nome}"

class ReceitaFavorita(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    receita = models.ForeignKey(Receita, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('usuario', 'receita')

    def __str__(self):
        return f"{self.usuario.username} - {self.receita.nome}"

main/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html', {})

def configuracoes(request):
    return render(request, 'main/configuracoes.html')

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-rBceEVmiTV4lKvIrl3GoNGjOjJ3ixU6tHk8nUjmzX6tlhQpvoNQV2NenkJqL+RkPhdM2z8LpogFqyhI6P4eC2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>{% block title %}SwiftSavor{% endblock %}</title>
</head>
<body>
    
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a href="{% url 'index' %}" class="navbar-brand">
                <img src="{% static 'main/logo.png' %}" alt="SwiftSavor Logo" height="100">
            </a>
           
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle px3" href="#" id="navbarDropdownUsuario" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Bem-vindo, {{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownUsuario">
                                <a class="dropdown-item" href="{% url 'configuracoes' %}">Configurações</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Sair</a>
                            </div>
                        </li>
        
                        {% if user.is_staff %}
                            <li class="nav-item">
                                <a class="nav-link px3" href="{% url 'admin_dashboard' %}">Dashboard</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle px3" href="#" id="navbarDropdownReceitas" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Receitas
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownReceitas">
                                    <a class="dropdown-item" href="{% url 'lista_receitas' %}">Lista de Receitas</a>
                                    <a class="dropdown-item" href="{% url 'cadastrar_receita' %}">Cadastrar Receita</a>
                                    <a class="dropdown-item" href="{% url 'receitas_recomendadas' %}">Receitas Recomendadas</a>
                                    <a class="dropdown-item" href="{% url 'favorites:receitas_favoritas' %}">Receitas Favoritas</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle px3" href="#" id="navbarDropdownIngredientes" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Ingredientes
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownIngredientes">
                                    <a class="dropdown-item" href="{% url 'selecionar_ingredientes' %}">Mercado</a>
                                    <a class="dropdown-item" href="{% url 'meus_ingredientes' %}">Minha Dispensa</a>
                                </div>
                            </li>
                        {% endif %}
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link px3" href="{% url 'login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link px3" href="{% url 'cadastrar_usuario' %}">Cadastrar</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    
        {% block content %}{% endblock %}
    </div>
    

    <footer class="footer mt-auto py-3">
        <div class="container-fluid">
            <p class="mb-0 w-100 text-center">&copy; 2024 SwiftSavor. Todos os direitos reservados.</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    {% block scripts %}
    <script src="{% static 'main/js/theme-toggle.js' %}"></script>
    {% endblock %}
</body>
</html>

main/templates/main/configuracoes.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Configurações{% endblock %}

{% block content %}
<div class="container-fluid mt-5 configuracoes-container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Configurações
                </div>
                <div class="card-body">
                    <h5 class="card-title">Segurança</h5>
                    <p class="card-text" id="pBlack">Ajuste as configurações de e-mail e senha.</p>
                    <div class="row">
                        <div class="col-md-6">
                            <form method="post" action="{% url 'trocar_email' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-block">Trocar Email</button>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <form method="post" action="{% url 'trocar_senha' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary btn-block">Trocar Senha</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Personalize sua experiência</h5>
                    <p class="card-text" id="pBlack">Ajuste as configurações do site para atender às suas preferências.</p>
                    <div class="row">
                        <div class="col-md-6">
                            <button id="theme-button" class="btn btn-primary btn-block" aria-label="Alternar Modo">Alternar Modo</button>
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
<div class="jumbotron mt-4 mx-auto text-center col-sm-10 col-md-8 col-lg-6 index-jumbotron">
    <h1 class="display-4">Bem-vindo ao SwiftSavor!</h1>
    <p class="lead">Encontre receitas incríveis para saborear.</p>
    <hr class="my-4">
    <p>Explorar receitas, cadastrar novas e muito mais!</p>
    {% if user.is_authenticated %}
        <a class="btn btn-primary btn-lg" href="{% url 'lista_receitas' %}" role="button">Veja Nossas Receitas</a>
    {% else %}
        <a class="btn btn-primary btn-lg" href="{% url 'cadastrar_usuario' %}" role="button">Cadastre-se para Explorar</a>
    {% endif %}
</div>

{% endblock %}